#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Vasco Marques
email: hi@vrqsworks.com
description: >- # this means to ignore newlines until "baseurl:"
  I build websites
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

social_links:
  - github:
    label: Github
    url: https://github.com/vrqs
  - x:
    label: X/Twitter
    url: https://x.com/vscmrqs
  - email:
    label: Email
    url: mailto:vrqsworks@gmail.com

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

permalink: /:title

sass:
  style: compressed